package com.hp.sla.analyser.view;

import com.hp.sla.analyser.model.SlaReportGenerator;
import com.hp.sla.analyser.model.SlaReportGenerationException;
import com.hp.sla.analyser.model.util.ExcelFilter;
import javax.swing.JOptionPane;

/**
 *
 * @author Benjamin Cisneros Barraza
 */
public class SlaAnalyserMainForm extends javax.swing.JFrame {

    /**
     * Creates new form SlaAnalyserMainForm
     */
    public SlaAnalyserMainForm() {
        super("SLA Report");
        setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        generateSLAButton = new javax.swing.JButton();
        file2NameLabel = new javax.swing.JLabel();
        file1Name = new javax.swing.JTextField();
        browseFile1Button = new javax.swing.JButton();
        browseFile2Button = new javax.swing.JButton();
        file1NameLabel = new javax.swing.JLabel();
        file2Name = new javax.swing.JTextField();

        fileChooser.setFileFilter(new ExcelFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        generateSLAButton.setText("Generate SLA Report");
        generateSLAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateSLAButtonActionPerformed(evt);
            }
        });

        file2NameLabel.setText("Assigment Audit File:");

        file1Name.setEditable(false);

        browseFile1Button.setText("Browse...");
        browseFile1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFile1ButtonActionPerformed(evt);
            }
        });

        browseFile2Button.setText("Browse...");
        browseFile2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFile2ButtonActionPerformed(evt);
            }
        });

        file1NameLabel.setText("Incident Ticket File:");

        file2Name.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(generateSLAButton, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addGap(208, 208, 208))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(file2NameLabel)
                    .addComponent(file1NameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(file1Name, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(file2Name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(browseFile2Button)
                    .addComponent(browseFile1Button))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(file1Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(file1NameLabel)
                    .addComponent(browseFile1Button))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(file2Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(browseFile2Button))
                    .addComponent(file2NameLabel))
                .addGap(16, 16, 16)
                .addComponent(generateSLAButton)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseFile1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFile1ButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            String fileName = file.toString();
            file1Name.setText(fileName);
        }
    }//GEN-LAST:event_browseFile1ButtonActionPerformed

    private void browseFile2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFile2ButtonActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File file = fileChooser.getSelectedFile();
            String fileName = file.toString();
            file2Name.setText(fileName);
        }
    }//GEN-LAST:event_browseFile2ButtonActionPerformed

    private void generateSLAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateSLAButtonActionPerformed
        SlaReportGenerator slaRG = new SlaReportGenerator();
        try {
            slaRG.generateReport(file1Name.getText(), file2Name.getText(), "C:\\Users\\ramirmal\\Downloads");
        } catch (SlaReportGenerationException SlaRGE) {
            JOptionPane.showMessageDialog(this, SlaRGE.getLocalizedMessage(), "Error Generating Report", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_generateSLAButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseFile1Button;
    private javax.swing.JButton browseFile2Button;
    private javax.swing.JTextField file1Name;
    private javax.swing.JLabel file1NameLabel;
    private javax.swing.JTextField file2Name;
    private javax.swing.JLabel file2NameLabel;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JButton generateSLAButton;
    // End of variables declaration//GEN-END:variables
}
